Algoritmo "Invertendo valores de variáveis"
// Aluno   : Carlos Alessandro Laurindo
// Data   : 10/03/2022


Var
variavelA,variavelB,variavelC : inteiro

Inicio
ESCREVAL ("Informe o valor 'A': ")
LEIA(variavelA)
ESCREVAL ("Informe o valor 'B': ")
LEIA(variavelB)
ESCREVAL ("Invertemos os valores das variáveis. Sendo assim:")
variavelC <- variavelB
variavelB <- variavelA
variavelA <- variavelC
ESCREVAL ("Variável A é: ",variavelA,".")
ESCREVAL ("Variável B é: ",variavelB,".")

Fimalgoritmo
