algoritmo "Estrutura para faça"
// Função : Compreender como funciona a estrutura
// Autor : Carlos Alessandro Laurindo
// Data : 18/03/2022
// Seção de Declarações
//Faça um algoritmo que mostre na tela 10 vezes a frase filosófica: “A careca do Silvio brilha, brilha a careca do Silvio”!
var
contadora: inteiro

inicio

para contadora de 1 ate 10 passo 1 faca
escreval(contadora," - A careca do Silvio brilha, brilha a careca do Silvio!")
fimpara

fimalgoritmo
